_id: 666afc35fc8df2002b36f214
name: Authentication
language: javascript
timeout: 12
triggers:
  register:
    type: http
    active: true
    options:
      method: Post
      path: /register
      preflight: true
  login:
    options:
      method: Post
      path: /login
      preflight: true
    type: http
    active: true
  onIdentityInsert:
    options:
      collection: identity
      type: INSERT
    type: database
    active: true
  fetchYandexToken:
    options:
      method: Get
      path: /fetch-yandex-token
      preflight: true
    type: http
    active: true
  authorizeYandex:
    options:
      method: Get
      path: /authorize-yandex
      preflight: true
    type: http
    active: true
  sendPasswordResetMail:
    options:
      method: Post
      path: /send-password-reset-mail
      preflight: true
    type: http
    active: true
  updateUserPassword:
    options:
      method: Post
      path: /update-user-password
      preflight: true
    type: http
    active: true
env:
  IDENTITY_FULL_ACCESS_KEY: "{IDENTITY_FULL_ACCESS_KEY}"
  USERS_BUCKET: "{USERS_BUCKET}"
  BUCKET_FULL_ACCESS_KEY: "{BUCKET_FULL_ACCESS_KEY}"
  USER_POLICY: "{USER_POLICY}"
  YANDEX_CLIENT_ID: "{YANDEX_CLIENT_ID}"
  YANDEX_CLIENT_SECRET_KEY: "{YANDEX_CLIENT_SECRET_KEY}"
  FORGOT_PASSWORD_REQUESTS_BUCKET: "{FORGOT_PASSWORD_REQUESTS_BUCKET}"
memoryLimit: 100
order: 0
